#ifndef __TESTFRAMECASE_DLL__
#define __TESTFRAMECASE_DLL__
bool Trans1TestFrameCase();
bool Trans2TestFrameCase();
bool Trans3TestFrameCase();
bool Trans4TestFrameCase();
bool Trans5TestFrameCase();
bool Trans6TestFrameCase();
bool Trans7TestFrameCase();
bool Trans8TestFrameCase();
bool Trans9TestFrameCase();
bool Trans10TestFrameCase();
bool Trans11TestFrameCase();
bool Trans12TestFrameCase();
bool Trans13TestFrameCase();
bool Trans14TestFrameCase();
bool Trans15TestFrameCase();
bool Trans16TestFrameCase();
bool Trans17TestFrameCase();
bool Trans18TestFrameCase();
bool Trans19TestFrameCase();
bool Trans20TestFrameCase();
bool Trans21TestFrameCase();
bool Trans22TestFrameCase();
bool Trans23TestFrameCase();
bool Trans24TestFrameCase();
bool Trans25TestFrameCase();
bool Trans26TestFrameCase();
bool Trans27TestFrameCase();
bool Trans28TestFrameCase();
bool Trans29TestFrameCase();
bool Trans30TestFrameCase();
#endif