#ifndef __CREATE_INDEX_H__
#define __CREATE_INDEX_H__
bool testIndexUpdate_SingleColumn_TestFrame();
bool testIndexUpdate_MultiColumn_TestFrame();
bool testIndexInsert_SingleColumn_TestFrame();
bool testIndexUpdate_InAnotherTrans_DLL_TestFrame();
bool testIndexInsert_SameScaKey_TestFrame();
bool testIndex_InAnotherTrans_TestFrame();
bool testIndex_Sort_TestFrame();
bool test_indexscan_dll_000_TestFrame();
bool test_indexscan_dll_001_TestFrame();
bool test_indexscan_dll_002_TestFrame();
bool test_indexscan_dll_003_TestFrame();
bool test_indexscan_dll_004_TestFrame();
bool test_indexscan_mark_restore_TestFrame();
bool test_index_transaction_001_TestFrame();
bool test_index_transaction_002_TestFrame();
bool test_index_transaction_003_TestFrame();
bool test_index_transaction_004_TestFrame();
bool test_index_transaction_005_TestFrame();
bool test_indexscan_LargeMount_dll_TestFrame();
bool test_index_uniqe_01_dll_TestFrame();
bool test_indexMult_SameCol_dll_TestFrame();
bool test_trans_index_DeleteRollback_TestFrame();
bool test_sequence_index_insert_TestFrame();
bool test_sequence_index_select_TestFrame();
bool test_sequence_index_001_insert_TestFrame();
bool test_sequence_index_001_select_TestFrame();
bool test_sequence_index_002_create_TestFrame();
bool test_sequence_index_002_select_TestFrame();
bool test_sequence_index_003_create_TestFrame();
bool test_sequence_index_003_insert_TestFrame();
bool test_sequence_index_003_select_TestFrame();
bool test_sequence_index_004_create_TestFrame();
bool test_sequence_index_004_insert_TestFrame();
bool test_sequence_index_004_select_TestFrame();
bool test_sequence_index_004_update_TestFrame();
bool test_sequence_index_005_insert_TestFrame();
bool test_sequence_index_005_update_01_TestFrame();
bool test_sequence_index_005_update_02_TestFrame();
bool test_sequence_index_005_update_03_TestFrame();
bool test_sequence_index_005_update_04_TestFrame();
bool test_sequence_index_005_update_05_TestFrame();
bool test_index_create_insert_dll_000_TestFrame();
#endif

