#ifndef ERR_NO_H
#define ERR_NO_H

#define INVALIDE_ARG 1
#define OPEN_RELATION_ERR 2
#define MEMORY_ALLOC_ERR 3
#define FIND_TRANSACTION_ERR 4
#define ENTRY_SET_NON_EXIST_ERR 5
#define HEAP_CREATE_ERR 6
#define FORBID_USE_ERR 7
#define RELCNT_ERR 8
#define HEAP_POINTER_ERR 9
#define MEAT_TABLE_DELETE_ERR 10
#define HEAP_INDEX_ERR 11
#define INDEX_CREATE_ERR 12
#define HEAP_OPEN_ERR 13
#define MEAT_TABLE_ERR 14
#define LOGIC_ERR       15
#define INVALID_TABLE_SAPCE 16
#define INVALID_TABLE_TYPE 17
#define INDEX_HAS_NO_HEAP 18
#define RELATION_NOT_IN_METATABLE 19
#define LARGE_OBJECT_ERROR 20


#endif //ERR_NO_H